from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd]
src     = Split("""
main.c
protocol/mem_list.c
driver/crc.c
driver/fal.c
driver/fal_flash.c
driver/fal_partition.c
driver/fal_rtt.c
driver/param.c
driver/rc4.c
driver/event.c
driver/utils.c
driver/icm20603.c
protocol/mcu.c
protocol/mcu_cmd.c
""")

CPPPATH += [cwd + '/protocol']
CPPPATH += [cwd + '/driver']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
